### ISSUE TITLE
Debug de validação de raia

### ISSUE THREAD

**Issue by brunolnetto** [flow-build/workflow-api#40]
_Questão_: Mensagem pouco descritiva `[LANE] "ERROR WHILE EVALUATING LANE RULE!"` em caso de exceção. Silencioso em caso de `false`. 

Sabido: O Flowbuild trabalha com eventos. Um evento é composto por [event, message, data]. No caso de exceção da função na rule, o evento é LANE.ERROR, a mensagem é [LANE] "ERROR WHILE EVALUATING LANE RULE!" e data é o error stack.

Sugestão: Implementar um listener de eventos do Flowbuild, pegar esse evento e salvar a data dele. Para capturar os dados desse evento, precisa alterar a API para escutar esse evento e tomar ações em cima disso. Existem 2 alternativas, cria um listener na API através de:

1.     fazer um printf no console dos dados;
2.     persistir no banco.

**Comment by gustavo-fdte** [comment]
this is not an issue dealt by the api.
the event emitter already send this info.
