### ISSUE TITLE
Add (prev_node_id, flow_path) to process table

### ISSUE THREAD

**Issue by brunolnetto** [flow-build/workflow-api#42]
Related to this issue: https://github.com/flow-build/workflow-api/issues/41

**What would you like to be added**:
**Previous id _node_id_ on current flow path** [String] and **flow path** (either a json with template _{'$step_number': '$node_id'}_ or ordered Array[node_id]: former is more robust then the latter) to table **process**

**Why is this needed**:
- Debug: It is easier then either to join or filter with table **process_state**;
- Analytics: It is easier then to join or to filter with table **process_state**;

- [] this issue need to update on docs? if yes where?
Wherever Workflow Database Model documentation is.

- [] this issue interact with a plugin or application? 
Workflow Database Model: create migrations and update table

**Comment by gustavo-fdte** [comment]
This should not be dealt by the api.
